import openai
openai.api_key = "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"

response = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "Given the AMR graph, parse the AMR graph to english sentence."},
        {"role": "user", "content": '(a / and\n      :op1 (h / have-03\n            :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n            :ARG1 (p / province :name (n2 / name :op1 \"Munich\")))\n      :op2 (f / fear-01\n            :ARG0 (c2 / country :name (n3 / name :op1 \"France\"))\n            :ARG1 h))'},
        {"role": "assistant", "content": "It seems like there are a lot of ways that could go wrong...I don't see why France would see you approaching/taking Munich--while I do nothing about it--and not immediately feel skittish"},
        {"role": "user", "content": '(p / propose-01\n      :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n      :ARG1 (a / and\n            :op1 (m / move-01\n                  :ARG1 (u / unit\n                        :mod c)\n                  :time (d2 / date-entity :year 1901\n                        :season (s / spring)))\n            :op2 (a2 / attack-01 :polarity -\n                  :ARG0 c\n                  :ARG1 (c3 / country :name (n6 / name :op1 \"Austria\")))\n            :op3 (d / defend-01 :polarity -\n                  :ARG0 c2\n                  :ARG1 (p2 / province :name (n7 / name :op1 \"Munich\")))\n            :op4 (b / build-01\n                  :ARG0 c2\n                  :ARG1 (a5 / army :quant 2))\n            :op5 (a3 / attack-01 :polarity -\n                  :ARG0 c\n                  :ARG1 c2)\n            :op6 (a4 / attack-01\n                  :ARG0 (a6 / and\n                        :op1 c\n                        :op2 c2)\n                  :time (d3 / date-entity :year 1902\n                        :season (s3 / spring)))\n            :op7 (f / fear-01 :polarity -\n                  :ARG0 (c4 / country :name (n10 / name :op1 \"France\"))))\n      :ARG3 (c2 / country :name (n2 / name :op1 \"Germany\")))'},
        {"role": "assistant", "content": "Yeah, I can\u2019t say I\u2019ve tried it and it works, cause I\u2019ve never tried it or seen it. But how I think it would work is (a) my Spring move looks like an attack on Austria, so it would not be surprising if you did not cover Munich. Then (b) you build two armies, which looks like we\u2019re really at war and you\u2019re going to eject me. Then we launch the attack in Spring. So there is really no part of this that would raise alarm bells with France.  All that said, I\u2019ve literally never done it before, and it does involve risk for you, so I\u2019m not offended or concerned if it\u2019s just not for you. I\u2019m happy to play more conventionally too. Up to you."},
        {"role": "user", "content": '(a / and\n      :op1 (r / reject-01\n            :ARG0 (c / country :name (n / name :op1 \"Germany\"))\n            :ARG1 (p2 / propose-01\n                  :ARG0 (c2 / country :name (n2 / name :op1 \"Italy\"))\n                  :ARG3 c))\n      :op2 (p / propose-01\n            :ARG0 c\n            :ARG1 (a2 / attack-01\n                  :ARG0 (a3 / and\n                        :op1 c\n                        :op2 c2)\n                  :ARG1 (c3 / country :name (n3 / name :op1 \"Austria\")))\n            :ARG3 c2))'},
        {"role": "assistant", "content": "I don't think I'm ready to go for that idea, however I'd be down for some good ol'-fashioned Austria-kicking?"},
        {"role": "user", "content": '(a / and\n      :op1 (a2 / ally-01\n            :ARG1 (a3 / and\n                  :op1 (c / country :name (n / name :op1 \"Italy\"))\n                  :op2 (c2 / country :name (n2 / name :op1 \"Austria\"))))\n      :op2 (p / propose-01\n            :ARG0 c\n            :ARG1 (a4 / ally-01\n                  :ARG1 (a5 / and\n                        :op1 c\n                        :op2 c2\n                        :op3 c3))\n            :ARG3 (c3 / country :name (n3 / name :op1 \"Germany\"))))'},
        {"role": "assistant", "content": "But I think I can get over \u201cLagergate\u201d and we can still be friends.   As of right now, I think Austria may be my most reliable ally. I\u2019m thinking I\u2019d like to play as a Central Trio if you have any interest in that. Thoughts?"},
        {"role": "user", "content": '(a / agree-01 :polarity -\n      :ARG0 (c2 / country :name (n / name :op1 \"Germany\"))\n      :ARG1 (a2 / ally-01\n            :ARG1 (a3 / and\n                  :op1 c2\n                  :op2 c))\n      :ARG2 (c / country :name (n2 / name :op1 \"Italy\")))'},
        {"role": "assistant", "content": "I appreciate the tip, but I'm wondering why you're so against ousting me from Munich if I haven't explicitly agreed to be your ally?"},
        {"role": "user", "content": '(p / propose-01\n      :ARG0 (c / country :name (n / name :op1 \"Germany\"))\n      :ARG1 (s / support-01\n            :ARG0 (c2 / country :name (n4 / name :op1 \"Italy\"))\n            :ARG1 (h / have-03\n                  :ARG0 c\n                  :ARG1 (p2 / province :name (n3 / name :op1 \"Marseille\")))\n            :time (d / date-entity :year 1902\n                  :season (f / fall)))\n      :ARG3 c2)'},
        {"role": "assistant", "content": "What would you think of helping me take Marseilles in two turns?"},
        {"role": "user", "content": '(p / propose-01\n      :ARG0 (c / country :name (n / name :op1 \"Germany\"))\n      :ARG1 (s / support-01\n            :ARG0 c\n            :ARG1 (h / have-03\n                  :ARG0 (c2 / country :name (n2 / name :op1 \"Italy\"))\n                  :ARG1 (p2 / province :name (n3 / name :op1 \"Marseille\"))))\n      :ARG3 c2)'},
        {"role": "assistant", "content": "Fair enough--I'll help you take it, then, but I'll need to deal with Belgium first."},
        {"role": "user", "content": '(p / propose-01\n      :ARG0 (c / country :name (n / name :op1 \"Germany\"))\n      :ARG1 (a / and\n            :op1 (s / support-01\n                  :ARG0 c\n                  :ARG1 (h / have-03\n                        :ARG0 (c2 / country :name (n2 / name :op1 \"England\"))\n                        :ARG1 (p2 / province :name (n3 / name :op1 \"Sweden\"))))\n            :op2 (s2 / support-01\n                  :ARG0 c2\n                  :ARG1 (m / move-01\n                        :ARG1 (u / unit\n                              :mod c)\n                        :ARG2 (p3 / province :name (n4 / name :op1 \"Belgium\")))))\n      :ARG3 c2)'},
        {"role": "assistant", "content": "I'm trying--I just offered to assist with taking Sweden in exchange for some assistance into Belgium...not sure if they'll go for it..."},
        {"role": "user", "content": '(m / move-01\n      :ARG1 (u / unit\n            :mod (c / country :name (n2 / name :op1 \"Italy\")))\n      :ARG2 (p / province :name (n3 / name :op1 \"Piedmont\"))\n      :polarity (a / amr-unknown)\n      :time (d / date-entity :year 1902\n            :season (s / spring)))'},
        {"role": "assistant", "content": "You're definitely telling the truth on that one. So can I count on you to move to piedmont this season?"},
        {"role": "user", "content": '(a / and\n      :op1 (a2 / attack-01\n            :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n            :ARG1 (c2 / country :name (n2 / name :op1 \"France\"))\n            :time (d / date-entity :year 1903\n                  :season (f / fall)))\n      :op2 (s / support-01\n            :ARG0 c\n            :ARG1 (h / hold-03\n                  :ARG1 (p / province :name (n3 / name :op1 \"Munich\")))))'},
        {"role": "assistant", "content": "I have good news! (1) I am finally attacking France this turn. (2) I will be supporting Munich to hold from Tyrolia.   Let\u2019s turn this game around, yes?"},
        {"role": "user", "content": '(a / and\n      :op1 (e / expect-01\n            :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n            :ARG1 (a2 / attack-01 :polarity -\n                  :ARG0 (c2 / country :name (n2 / name :op1 \"England\"))\n                  :ARG1 (c3 / country :name (n3 / name :op1 \"Germany\"))\n                  :time (d / date-entity :year 1903\n                        :season (f / fall))))\n      :op2 (m / move-01 :polarity - :mode imperative\n            :ARG1 (u / unit\n                  :mod c3\n                  :location (p / province :name (n4 / name :op1 \"Munich\")))\n            :purpose (s / support-01\n                  :ARG0 c\n                  :ARG1 (h / hold-03\n                        :ARG0 c3\n                        :ARG1 p))))'},
        {"role": "assistant", "content": "I am pretty sure that England is not attacking you this turn. And I am committed to supporting Munich holding. Make sure you don\u2019t move Munich so that it can take my support."},
        {"role": "user", "content": '(p / propose-01\n      :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n      :ARG1 (a / and\n            :op1 (s / support-01\n                  :ARG0 (u / unit\n                        :mod (c2 / country :name (n2 / name :op1 \"Germany\"))\n                        :location (p2 / province :name (n3 / name :op1 \"Kiel\")))\n                  :ARG1 (h / hold-03\n                        :ARG0 (u2 / unit\n                              :mod c2\n                              :location p3)\n                        :ARG1 (p3 / province :name (n4 / name :op1 \"Berlin\"))))\n            :op2 (s2 / support-01\n                  :ARG0 u2\n                  :ARG1 (h2 / hold-03\n                        :ARG1 (p4 / province :name (n5 / name :op1 \"Munich\"))))\n            :op3 (m / move-01\n                  :ARG1 (f / fleet\n                        :location (s3 / sea :name (n6 / name :op1 \"Heligoland\" :op2 \"Bight\"))\n                        :mod c2)\n                  :ARG2 (p5 / province :name (n7 / name :op1 \"Holland\")))\n            :op4 (s4 / support-01\n                  :ARG0 (u4 / unit\n                        :location p4)\n                  :ARG1 h))\n      :ARG3 c2)'},
        {"role": "assistant", "content": "I suggest that you order: Kiel Support Berlin holding Berlin Support Munich holding Helg to Holland Munich Support Berlin holding"},
        {"role": "user", "content": '(a / and\n      :op1 (s / support-01\n            :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n            :ARG1 (h / hold-03\n                  :ARG1 (p / province :name (n2 / name :op1 \"Munich\"))))\n      :op2 (p2 / propose-01\n            :ARG0 c\n            :ARG1 (d / defend-01\n                  :ARG0 (c2 / country :name (n5 / name :op1 \"Russia\"))\n                  :ARG1 c2\n                  :ARG2 (c3 / country :name (n4 / name :op1 \"Austria\")))\n            :ARG3 c2))'},
        {"role": "assistant", "content": "I will be supporting Munich to hold again. And I\u2019ll be trying to get Russia to back off your flank and protect himself against an Austrian stab that is coming."},
        {"role": "user", "content": '(p / propose-01\n      :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n      :ARG1 (a / and\n            :op1 (w / warn-01\n                  :ARG0 (c2 / country :name (n7 / name :op1 \"Germany\"))\n                  :ARG1 (a2 / attack-01\n                        :ARG0 (c4 / country :name (n4 / name :op1 \"Austria\"))\n                        :ARG1 c3)\n                  :ARG2 (c3 / country :name (n3 / name :op1 \"Russia\")))\n            :op2 (p2 / propose-01\n                  :ARG0 c2\n                  :ARG1 (a3 / and\n                        :op1 (s / support-01\n                              :ARG0 c3\n                              :ARG1 (m / move-01\n                                    :ARG1 (u / unit\n                                          :mod c2)\n                                    :ARG2 (p3 / province :name (n5 / name :op1 \"Denmark\"))))\n                        :op2 (s2 / support-01\n                              :ARG0 c2\n                              :ARG1 (m2 / move-01\n                                    :ARG1 (u2 / unit\n                                          :mod c3)\n                                    :ARG2 (p4 / province :name (n6 / name :op1 \"Sweden\")))))\n                  :ARG2 c3\n                  :ARG3 c3))\n      :ARG3 c2)'},
        {"role": "assistant", "content": "Two bits of advice: #1 I suggest you tell Russia that Austria is coming for him. You really want Russia to move Sil back to Gal. You might also suggest to Russia that is he supports you to Denmark, you will then support Russia back to Sweden. I don\u2019t know yet if it actually makes sense to do that, but you want Russia thinking that you are eager to work with him. He\u2019ll be hoping for a reason to break off his attack on you at this point."},
        {"role": "user", "content": '(p / propose-01\n      :ARG0 (c / country :name (n / name :op1 \"Germany\"))\n      :ARG3 (c2 / country :name (n2 / name :op1 \"Russia\")))'},
        {"role": "assistant", "content": "God, I hope so! I'm attempting to make that deal with russia now...and I'm talking with England re: Belgium"},
        # {"role": "user", "content": '(a / and\n      :op1 (e / expect-01\n            :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n            :ARG1 (a2 / attack-01 :polarity -\n                  :ARG0 (c2 / country :name (n2 / name :op1 \"Russia\"))\n                  :ARG1 (u / unit\n                        :mod (c3 / country :name (n3 / name :op1 \"Germany\"))\n                        :location (p2 / province :name (n4 / name :op1 \"Burgundy\")))))\n      :op2 (p / propose-01\n            :ARG0 c\n            :ARG1 (a3 / and\n                  :op1 (m / move-01\n                        :ARG1 (u2 / unit\n                              :location (p3 / province :name (n5 / name :op1 \"Munich\"))\n                              :mod c3)\n                        :ARG2 p2)\n                  :op2 (m2 / move-01\n                        :ARG1 (u3 / unit\n                              :location (p4 / province :name (n6 / name :op1 \"Ruhr\"))\n                              :mod c3)\n                        :ARG2 (p5 / province :name (n7 / name :op1 \"Belgium\")))\n                  :op3 (s / support-01\n                        :ARG0 (u4 / unit\n                              :location (p6 / province :name (n8 / name :op1 \"Holland\")))\n                        :ARG1 m2)\n                  :op4 (m3 / move-01\n                        :ARG1 (u5 / unit\n                              :location (p7 / province :name (n9 / name :op1 \"Berlin\"))\n                              :mod c3)\n                        :ARG2 (p8 / province :name (n10 / name :op1 \"Kiel\"))))\n            :ARG3 c3))'},
        # {"role": "assistant", "content": "I do think a move to Burgundy makes sense for you this turn, and I can\u2019t imagine Russia attacking you here. He has a serious Austria problem.   I suggest this: Mun - Bur Ruh - Bel Hol Support Ruh - Bel  Ber - Kie  Tell Russia that the last thing in the world you want to see is Austria run him over, and you\u2019re willing to help keep Russia viable if necessary (you\u2019re angling for Russia to disband his northern holdings this turn)."},
        # {"role": "user", "content": '(p / propose-01\n      :ARG0 (c / country :name (n / name :op1 \"Germany\"))\n      :ARG1 (a / and\n            :op1 (s / support-01\n                  :ARG0 c2\n                  :ARG1 (t / transport-01\n                        :ARG0 (f / fleet\n                              :mod c2)\n                        :ARG1 (u / unit\n                              :location (p2 / province :name (n3 / name :op1 \"Piedmont\")))\n                        :ARG3 (p3 / province :name (n4 / name :op1 \"Spain\")))\n                  :instrument (f2 / fleet\n                        :location (s2 / sea :name (n5 / name :op1 \"Western\" :op2 \"Mediterranean\"))\n                        :mod (c2 / country :name (n2 / name :op1 \"Italy\"))))\n            :op2 (m / move-01\n                  :ARG1 (u3 / unit\n                        :location (p4 / province :name (n6 / name :op1 \"Tyrolia\"))\n                        :mod c2)\n                  :ARG2 p2))\n      :ARG3 c2)'},
        # {"role": "assistant", "content": "England and I were talking about your moves for this season--what do you think of convoying Pie into Spa, supporting this with Wes, and then moving Tyr into Pie?"},
        # {"role": "user", "content": '(a / and\n      :op1 (p / possible-01 :polarity -\n            :ARG1 (m / move-01\n                  :ARG1 (u / unit\n                        :mod (c / country :name (n / name :op1 \"Germany\")))\n                  :ARG2 (p2 / province :name (n2 / name :op1 \"Gascony\"))\n                  :time (d / date-entity :year 1905\n                        :season (f / fall))))\n      :op2 (p3 / possible-01\n            :ARG1 (t / tell-01\n                  :ARG0 (c2 / country :name (n3 / name :op1 \"Italy\"))\n                  :ARG1 (a2 / and\n                        :op1 (s / support-01\n                              :ARG0 c\n                              :ARG1 (m3 / move-01\n                                    :ARG1 (u2 / unit\n                                          :location (p4 / province :name (n4 / name :op1 \"Munich\")))\n                                    :ARG2 (p5 / province :name (n5 / name :op1 \"Burgundy\"))))\n                        :op2 (m2 / move-01 :polarity -\n                              :ARG1 (u3 / unit\n                                    :location (p6 / province :name (n6 / name :op1 \"Kiel\")))\n                              :ARG2 (p7 / province :name (n7 / name :op1 \"Ruhr\"))))\n                  :ARG2 c)\n            :condition (t2 / tell-01\n                  :ARG0 c\n                  :ARG2 c2)))'},
        # {"role": "assistant", "content": "Sorry I won't be able to cut off Gascony this turn...I probably should have just told you my moves; you could have advised me that supporting Mun-Bur was more important than Kie-Ruh"},
        # {"role": "user", "content": '(p / propose-01\n      :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n      :ARG1 (a / and\n            :op1 (m / move-01\n                  :ARG1 (u / unit\n                        :location (p2 / province :name (n3 / name :op1 \"Kiel\")))\n                  :ARG2 (p3 / province :name (n4 / name :op1 \"Denmark\")))\n            :op2 (s / support-01\n                  :ARG1 (h / hold-03\n                        :ARG1 p3)\n                  :instrument (u2 / unit\n                        :location (p4 / province :name (n5 / name :op1 \"Holland\"))))\n            :op3 (m2 / move-01\n                  :ARG1 (u3 / unit\n                        :location (p5 / province :name (n6 / name :op1 \"Ruhr\")))\n                  :ARG2 (p6 / province :name (n7 / name :op1 \"Burgundy\")))\n            :op4 (s2 / support-01\n                  :ARG1 m2\n                  :instrument (a2 / and\n                        :op1 (u4 / unit\n                              :location (p7 / province :name (n8 / name :op1 \"Munich\")))\n                        :op2 (u5 / unit\n                              :location p7))))\n      :ARG3 (c2 / country :name (n2 / name :op1 \"Germany\")))'},
        # {"role": "assistant", "content": "No worries. We\u2019ll crack this but eventually.   Here is my suggestion for this turn: Kie - Den Hol S Bel holding Bel S Ruh - Bur Mun S Ruh - Bur Ruh - Bur"},
        # {"role": "user", "content": '(a / and\n      :op1 (p / propose-01\n            :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n            :ARG1 (p2 / propose-01\n                  :ARG0 (c2 / country :name (n2 / name :op1 \"Germany\"))\n                  :ARG1 (a2 / and\n                        :op1 (h / have-03\n                              :ARG0 (c3 / country :name (n3 / name :op1 \"England\"))\n                              :ARG1 (a3 / and\n                                    :op1 (p3 / province :name (n4 / name :op1 \"Sweden\"))\n                                    :op2 (p4 / province :name (n5 / name :op1 \"St.\" :op2 \"Petersburg\"))))\n                        :op2 (h2 / have-03\n                              :ARG0 c2\n                              :ARG1 (p5 / province :name (n6 / name :op1 \"Denmark\"))))\n                  :ARG3 c3)\n            :ARG3 c2)\n      :op2 (a4 / ally-01\n            :ARG1 (a5 / and\n                  :op1 c\n                  :op2 c2)\n            :ARG3 (c4 / country :name (n7 / name :op1 \"France\"))))'},
        # {"role": "assistant", "content": "I think you should suggest to England that he gets Sweden and St Petersburg, while you get Denmark back. That\u2019s only fair, as you have been a loyal ally in the fight against France and you plan to continue to do that."},
        {"role": "user", "content": '(p / propose-01\n      :ARG0 (c / country :name (n / name :op1 \"Germany\"))\n      :ARG1 (a / and\n            :op1 (a2 / attack-01\n                  :ARG0 c2\n                  :ARG1 (c3 / country :name (n3 / name :op1 \"France\"))\n                  :instrument (f / fleet))\n            :op2 (a3 / attack-01\n                  :ARG0 c\n                  :ARG1 c3\n                  :instrument (u / unit\n                        :location (p2 / province :name (n4 / name :op1 \"Burgundy\"))))\n            :op3 (h / have-03\n                  :ARG0 c2\n                  :ARG1 (a4 / and\n                        :op1 (p3 / province :name (n5 / name :op1 \"Marseille\"))\n                        :op2 (p4 / province :name (n6 / name :op1 \"Spain\"))\n                        :op3 (p5 / province :name (n7 / name :op1 \"Portugal\"))))\n            :op4 (h2 / have-03\n                  :ARG0 c\n                  :ARG1 (a5 / and\n                        :op1 (p6 / province :name (n8 / name :op1 \"Brest\"))\n                        :op2 (p7 / province :name (n9 / name :op1 \"Paris\")))))\n      :ARG3 (c2 / country :name (n2 / name :op1 \"Italy\")))'}
        #{"role": "user", "content": '(f / fear-01\n      :ARG0 (c / country :name (n / name :op1 \"Germany\"))\n      :ARG1 (m / move-01\n            :ARG1 (u / unit\n                  :mod (c2 / country :name (n2 / name :op1 \"Italy\")))\n            :ARG2 (p / province :name (n3 / name :op1 \"Tyrolia\"))))'}
        #{"role": "user", "content": '(s / support-01\n      :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n      :ARG1 (a / attack-01\n            :ARG1 (p2 / province :name (n3 / name :op1 \"Trieste\")))\n      :instrument (u / unit\n            :location (p / province :name (n2 / name :op1 \"Tyrolia\"))))'}
        #{"role": "user", "content": '(p / possible-01\n      :ARG1 (m / move-01\n            :ARG1 (a / army\n                  :mod (c / country :name (n / name :op1 \"Italy\")))\n            :ARG2 (p2 / province :name (n2 / name :op1 \"Munich\"))))'}
        #{"role": "user", "content": '(p / possible-01\n      :ARG1 (r / retreat-01\n            :ARG1 (u / unit\n                  :mod (c / country :name (n / name :op1 \"Austria\")))))'}
        #{"role": "user", "content": '(p / possible-01\n      :ARG1 (a / and\n            :op1 (p2 / prevent-01\n                  :ARG0 (c / country :name (n / name :op1 \"Turkey\"))\n                  :ARG1 (s / support-01\n                        :ARG0 (u / unit\n                              :location (p3 / province :name (n2 / name :op1 \"Trieste\")))\n                        :ARG1 (p4 / province :name (n3 / name :op1 \"Venice\")))\n                  :condition (a2 / attack-01\n                        :ARG0 c\n                        :ARG1 p3))\n            :op2 (r / retreat-01\n                  :ARG1 (f / fleet\n                        :location (s2 / sea :name (n4 / name :op1 \"Ionian\" :op2 \"Sea\")))\n                  :destination (s3 / sea :name (n5 / name :op1 \"Adriatic\" :op2 \"Sea\")))\n            :op3 (r2 / retreat-01\n                  :ARG1 f\n                  :destination (o / or\n                        :op1 (p5 / province :name (n6 / name :op1 \"Tunisia\"))\n                        :op2 (p6 / province :name (n7 / name :op1 \"Naples\"))))))'}
        #{"role": "user", "content": '(e / expect-01\n      :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n      :ARG1 (a / and\n            :op1 (m / move-01\n                  :ARG1 (u / unit\n                        :mod (c2 / country :name (n2 / name :op1 \"Turkey\")))\n                  :ARG2 (p / province :name (n3 / name :op1 \"Trieste\"))\n                  :purpose (d / defend-01\n                        :ARG0 c2\n                        :ARG1 p))\n            :op2 (h / have-03\n                  :ARG0 c2\n                  :ARG1 (p2 / province :name (n4 / name :op1 \"Greece\"))\n                  :instrument (a2 / and\n                        :op1 (u2 / unit\n                              :mod c2\n                              :location (p3 / province :name (n5 / name :op1 \"Bulgaria\")))\n                        :op2 (f / fleet\n                              :mod c2\n                              :location (s / sea :name (n6 / name :op1 \"Aegean\" :op2 \"Sea\")))))))'}
        #{"role": "user", "content": '(a / and\n      :op1 (p / possible-01\n            :ARG1 (b / betray-01\n                  :ARG0 (c / country :name (n / name :op1 \"Turkey\"))\n                  :ARG1 (c2 / country :name (n2 / name :op1 \"Italy\"))\n                  :condition (s / support-01 :polarity -\n                        :ARG0 c2\n                        :ARG1 (m / move-01\n                              :ARG1 (u / unit\n                                    :mod c)\n                              :ARG2 (p2 / province :name (n3 / name :op1 \"Tunisia\"))))))\n      :op2 (p3 / propose-01\n            :ARG0 c\n            :ARG1 (s2 / support-01\n                  :ARG0 c\n                  :ARG1 (m2 / move-01\n                        :ARG1 (u2 / unit\n                              :mod c2)\n                        :ARG2 (p4 / province :name (n4 / name :op1 \"Trieste\"))))\n            :ARG3 c2))'}
        #{"role": "user", "content": '(a / and\n      :op1 (h / have-03\n            :ARG0 (c / country :name (n / name :op1 \"Turkey\"))\n            :ARG1 (p / province :name (n2 / name :op1 \"Greece\"))\n            :time (d / date-entity :year 1904))\n      :op2 (a2 / agree-01\n            :ARG0 c\n            :ARG1 (s / support-01\n                  :ARG0 c\n                  :ARG1 (m / move-01\n                        :ARG1 (u / unit\n                              :mod c2)\n                        :ARG2 (p2 / province :name (n4 / name :op1 \"Trieste\")))\n                  :condition (h2 / have-03 :polarity -\n                        :ARG0 c2\n                        :ARG1 (p3 / province :name (n5 / name :op1 \"Venice\"))))\n            :ARG2 (c2 / country :name (n3 / name :op1 \"Italy\"))))'}
        #{"role": "user", "content": '(p / possible-01\n      :ARG1 (h / have-03\n            :ARG0 (c / country :name (n / name :op1 \"Italy\"))\n            :ARG1 (a / and\n                  :op1 (p2 / province :name (n2 / name :op1 \"Trieste\"))\n                  :op2 (p3 / province :name (n3 / name :op1 \"Venice\")))))'}
    ],
  temperature = 0.2
)
print(response)